#!/usr/bin/env python3
"""
ROBUST BLEND FILE TESTING SYSTEM
================================

Comprehensive testing system for validating Blender blend files generated by
the mutating cube animation system. Includes scene validation, animation checks,
and quality assurance.

Features:
- Scene structure validation
- Animation keyframe verification
- Shape key functionality testing
- Material and lighting checks
- Performance metrics
- Quality assurance reports
"""

import json
import os
import subprocess
import sys
from pathlib import Path
from typing import Dict, List, Tuple, Optional, Any
import time


class BlendFileTester:
    """Robust testing system for Blender blend files."""
    
    def __init__(self, blend_path: str):
        self.blend_path = Path(blend_path)
        self.test_results = {
            'file_exists': False,
            'scene_structure': {},
            'animations': {},
            'materials': {},
            'lighting': {},
            'performance': {},
            'quality_issues': [],
            'recommendations': []
        }
        
    def run_comprehensive_test(self) -> Dict[str, Any]:
        """Run comprehensive test suite on the blend file."""
        print(f"🧪 Running comprehensive test on: {self.blend_path}")
        
        # Test 1: File existence and basic validation
        self._test_file_existence()
        
        # Test 2: Scene structure validation
        self._test_scene_structure()
        
        # Test 3: Animation validation
        self._test_animations()
        
        # Test 4: Material validation
        self._test_materials()
        
        # Test 5: Lighting validation
        self._test_lighting()
        
        # Test 6: Performance metrics
        self._test_performance()
        
        # Test 7: Quality assurance
        self._test_quality_assurance()
        
        # Generate recommendations
        self._generate_recommendations()
        
        return self.test_results
    
    def _test_file_existence(self):
        """Test if blend file exists and is valid."""
        print("📁 Testing file existence...")
        
        if not self.blend_path.exists():
            self.test_results['file_exists'] = False
            self.test_results['quality_issues'].append("Blend file does not exist")
            return
        
        if not self.blend_path.suffix == '.blend':
            self.test_results['quality_issues'].append("File is not a .blend file")
            return
        
        # Check file size
        file_size = self.blend_path.stat().st_size
        if file_size < 1024:  # Less than 1KB
            self.test_results['quality_issues'].append("Blend file is too small (likely empty)")
        elif file_size > 100 * 1024 * 1024:  # More than 100MB
            self.test_results['quality_issues'].append("Blend file is very large (may cause performance issues)")
        
        self.test_results['file_exists'] = True
        self.test_results['file_size'] = file_size
        print(f"✅ File exists: {file_size / 1024 / 1024:.2f} MB")
    
    def _test_scene_structure(self):
        """Test scene structure and objects."""
        print("🏗️ Testing scene structure...")
        
        # Use Blender Python API to inspect scene
        inspection_script = f'''
import bpy
import json

# Load the blend file
bpy.ops.wm.open_mainfile(filepath="{self.blend_path}")

scene_info = {{
    "objects": [],
    "materials": [],
    "lights": [],
    "cameras": [],
    "meshes": []
}}

# Get all objects
for obj in bpy.context.scene.objects:
    obj_info = {{
        "name": obj.name,
        "type": obj.type,
        "location": list(obj.location),
        "rotation": list(obj.rotation_euler),
        "scale": list(obj.scale),
        "visible": obj.visible_get()
    }}
    
    if obj.type == 'MESH':
        obj_info["vertices"] = len(obj.data.vertices)
        obj_info["polygons"] = len(obj.data.polygons)
        obj_info["shape_keys"] = len(obj.data.shape_keys.key_blocks) if obj.data.shape_keys else 0
    
    scene_info["objects"].append(obj_info)

# Get materials
for mat in bpy.data.materials:
    scene_info["materials"].append({{
        "name": mat.name,
        "use_nodes": mat.use_nodes,
        "node_count": len(mat.node_tree.nodes) if mat.use_nodes else 0
    }})

# Get lights
for light in bpy.data.lights:
    scene_info["lights"].append({{
        "name": light.name,
        "type": light.type,
        "energy": light.energy,
        "color": list(light.color)
    }})

# Get cameras
for camera in bpy.data.cameras:
    scene_info["cameras"].append({{
        "name": camera.name,
        "type": camera.type,
        "lens": camera.lens,
        "sensor_width": camera.sensor_width
    }})

# Get meshes
for mesh in bpy.data.meshes:
    scene_info["meshes"].append({{
        "name": mesh.name,
        "vertices": len(mesh.vertices),
        "edges": len(mesh.edges),
        "polygons": len(mesh.polygons),
        "shape_keys": len(mesh.shape_keys.key_blocks) if mesh.shape_keys else 0
    }})

# Scene properties
scene = bpy.context.scene
scene_info["scene_properties"] = {{
    "frame_start": scene.frame_start,
    "frame_end": scene.frame_end,
    "fps": scene.render.fps,
    "resolution_x": scene.render.resolution_x,
    "resolution_y": scene.render.resolution_y,
    "engine": scene.render.engine
}}

print(json.dumps(scene_info))
'''
        
        try:
            result = self._run_blender_script(inspection_script)
            if result['success']:
                scene_data = json.loads(result['output'])
                self.test_results['scene_structure'] = scene_data
                self._validate_scene_structure(scene_data)
            else:
                self.test_results['quality_issues'].append(f"Scene inspection failed: {result['error']}")
        except Exception as e:
            self.test_results['quality_issues'].append(f"Scene structure test failed: {e}")
    
    def _validate_scene_structure(self, scene_data: Dict):
        """Validate scene structure based on expected mutating cube setup."""
        print("🔍 Validating scene structure...")
        
        # Check for mutating cube
        cube_found = False
        for obj in scene_data.get('objects', []):
            if 'MutatingCube' in obj['name'] and obj['type'] == 'MESH':
                cube_found = True
                
                # Check subdivision
                if obj.get('vertices', 0) < 1000:
                    self.test_results['quality_issues'].append("Cube has insufficient subdivision for smooth deformation")
                
                # Check shape keys
                if obj.get('shape_keys', 0) < 5:
                    self.test_results['quality_issues'].append("Cube has insufficient shape keys for complex deformation")
                
                break
        
        if not cube_found:
            self.test_results['quality_issues'].append("Mutating cube object not found")
        
        # Check for camera
        cameras = [obj for obj in scene_data.get('objects', []) if obj['type'] == 'CAMERA']
        if not cameras:
            self.test_results['quality_issues'].append("No camera found in scene")
        
        # Check for lights
        lights = [obj for obj in scene_data.get('objects', []) if obj['type'] == 'LIGHT']
        if len(lights) < 2:
            self.test_results['quality_issues'].append("Insufficient lighting setup")
        
        # Check materials
        materials = scene_data.get('materials', [])
        if not materials:
            self.test_results['quality_issues'].append("No materials found")
        
        print(f"✅ Scene structure validation complete")
    
    def _test_animations(self):
        """Test animation data and keyframes."""
        print("🎬 Testing animations...")
        
        animation_script = f'''
import bpy
import json

# Load the blend file
bpy.ops.wm.open_mainfile(filepath="{self.blend_path}")

animation_info = {{
    "actions": [],
    "fcurves": [],
    "keyframes": []
}}

# Get all actions
for action in bpy.data.actions:
    action_info = {{
        "name": action.name,
        "fcurves": len(action.fcurves),
        "frame_range": [action.frame_range[0], action.frame_range[1]] if action.frame_range else [0, 0]
    }}
    
    # Get fcurve details
    fcurve_details = []
    for fcurve in action.fcurves:
        fcurve_info = {{
            "data_path": fcurve.data_path,
            "keyframe_count": len(fcurve.keyframe_points),
            "extrapolation": fcurve.extrapolation,
            "keyframes": []
        }}
        
        # Get keyframe details
        for keyframe in fcurve.keyframe_points:
            keyframe_info = {{
                "frame": keyframe.co[0],
                "value": keyframe.co[1],
                "interpolation": keyframe.interpolation,
                "handle_left_type": keyframe.handle_left_type,
                "handle_right_type": keyframe.handle_right_type
            }}
            fcurve_info["keyframes"].append(keyframe_info)
        
        fcurve_details.append(fcurve_info)
    
    action_info["fcurve_details"] = fcurve_details
    animation_info["actions"].append(action_info)

# Get scene frame range
scene = bpy.context.scene
animation_info["scene_frames"] = {{
    "frame_start": scene.frame_start,
    "frame_end": scene.frame_end,
    "fps": scene.render.fps
}}

print(json.dumps(animation_info))
'''
        
        try:
            result = self._run_blender_script(animation_script)
            if result['success']:
                animation_data = json.loads(result['output'])
                self.test_results['animations'] = animation_data
                self._validate_animations(animation_data)
            else:
                self.test_results['quality_issues'].append(f"Animation inspection failed: {result['error']}")
        except Exception as e:
            self.test_results['quality_issues'].append(f"Animation test failed: {e}")
    
    def _validate_animations(self, animation_data: Dict):
        """Validate animation data."""
        print("🔍 Validating animations...")
        
        actions = animation_data.get('actions', [])
        if not actions:
            self.test_results['quality_issues'].append("No animation actions found")
            return
        
        # Check for shape key animations
        shape_key_animations = 0
        for action in actions:
            for fcurve_detail in action.get('fcurve_details', []):
                if 'key_blocks' in fcurve_detail.get('data_path', ''):
                    shape_key_animations += 1
        
        if shape_key_animations < 5:
            self.test_results['quality_issues'].append("Insufficient shape key animations")
        
        # Check keyframe interpolation
        bezier_count = 0
        total_keyframes = 0
        
        for action in actions:
            for fcurve_detail in action.get('fcurve_details', []):
                for keyframe in fcurve_detail.get('keyframes', []):
                    total_keyframes += 1
                    if keyframe.get('interpolation') == 'BEZIER':
                        bezier_count += 1
        
        if total_keyframes > 0:
            bezier_ratio = bezier_count / total_keyframes
            if bezier_ratio < 0.8:
                self.test_results['quality_issues'].append("Too many linear keyframes (should use BEZIER for smooth animation)")
        
        print(f"✅ Animation validation complete: {shape_key_animations} shape key animations, {bezier_ratio:.1%} BEZIER interpolation")
    
    def _test_materials(self):
        """Test material setup."""
        print("🎨 Testing materials...")
        
        # Material validation is done in scene structure test
        materials = self.test_results['scene_structure'].get('materials', [])
        
        if not materials:
            self.test_results['quality_issues'].append("No materials found")
        else:
            # Check for node-based materials
            node_materials = [mat for mat in materials if mat.get('use_nodes', False)]
            if not node_materials:
                self.test_results['quality_issues'].append("No node-based materials found")
            
            # Check for complex materials
            complex_materials = [mat for mat in materials if mat.get('node_count', 0) > 5]
            if not complex_materials:
                self.test_results['quality_issues'].append("Materials appear too simple")
        
        print("✅ Material testing complete")
    
    def _test_lighting(self):
        """Test lighting setup."""
        print("💡 Testing lighting...")
        
        # Lighting validation is done in scene structure test
        lights = self.test_results['scene_structure'].get('lights', [])
        
        if len(lights) < 2:
            self.test_results['quality_issues'].append("Insufficient lighting setup")
        else:
            # Check for different light types
            light_types = set(light.get('type', '') for light in lights)
            if len(light_types) < 2:
                self.test_results['quality_issues'].append("Limited variety in lighting types")
            
            # Check light energy values
            for light in lights:
                energy = light.get('energy', 0)
                if energy < 0.1 or energy > 10:
                    self.test_results['quality_issues'].append(f"Light '{light.get('name', 'Unknown')}' has unusual energy value: {energy}")
        
        print("✅ Lighting testing complete")
    
    def _test_performance(self):
        """Test performance metrics."""
        print("⚡ Testing performance...")
        
        scene_data = self.test_results['scene_structure']
        
        # Check polygon count
        total_polygons = 0
        for mesh in scene_data.get('meshes', []):
            total_polygons += mesh.get('polygons', 0)
        
        if total_polygons > 100000:
            self.test_results['quality_issues'].append(f"High polygon count ({total_polygons}) may cause performance issues")
        
        # Check shape key count
        total_shape_keys = 0
        for mesh in scene_data.get('meshes', []):
            total_shape_keys += mesh.get('shape_keys', 0)
        
        if total_shape_keys > 20:
            self.test_results['quality_issues'].append(f"High shape key count ({total_shape_keys}) may cause performance issues")
        
        self.test_results['performance'] = {
            'total_polygons': total_polygons,
            'total_shape_keys': total_shape_keys,
            'object_count': len(scene_data.get('objects', []))
        }
        
        print(f"✅ Performance testing complete: {total_polygons} polygons, {total_shape_keys} shape keys")
    
    def _test_quality_assurance(self):
        """Run quality assurance checks."""
        print("🔍 Running quality assurance...")
        
        # Check render settings
        scene_props = self.test_results['scene_structure'].get('scene_properties', {})
        
        if scene_props.get('resolution_x', 0) < 1280:
            self.test_results['quality_issues'].append("Low resolution render settings")
        
        if scene_props.get('fps', 0) < 24:
            self.test_results['quality_issues'].append("Low frame rate")
        
        # Check frame range
        frame_start = scene_props.get('frame_start', 0)
        frame_end = scene_props.get('frame_end', 0)
        frame_count = frame_end - frame_start + 1
        
        if frame_count < 30:
            self.test_results['quality_issues'].append("Short animation duration")
        
        print("✅ Quality assurance complete")
    
    def _generate_recommendations(self):
        """Generate recommendations based on test results."""
        print("💡 Generating recommendations...")
        
        recommendations = []
        
        # Performance recommendations
        if self.test_results['performance'].get('total_polygons', 0) > 50000:
            recommendations.append("Consider reducing polygon count for better performance")
        
        if self.test_results['performance'].get('total_shape_keys', 0) > 15:
            recommendations.append("Consider optimizing shape key count for better performance")
        
        # Quality recommendations
        if any('insufficient' in issue.lower() for issue in self.test_results['quality_issues']):
            recommendations.append("Increase subdivision and shape key count for better deformation")
        
        if any('linear' in issue.lower() for issue in self.test_results['quality_issues']):
            recommendations.append("Use BEZIER interpolation for smoother animations")
        
        # Lighting recommendations
        if any('lighting' in issue.lower() for issue in self.test_results['quality_issues']):
            recommendations.append("Add more lights or improve lighting setup for better visual quality")
        
        self.test_results['recommendations'] = recommendations
        print(f"✅ Generated {len(recommendations)} recommendations")
    
    def _run_blender_script(self, script_content: str) -> Dict[str, Any]:
        """Run a Blender script and return results."""
        # Try to find Blender executable
        blender_paths = [
            '/Applications/Blender.app/Contents/MacOS/Blender',
            'blender',
            os.path.expanduser('~/bin/blender'),
            '/usr/bin/blender',
            'C:\\Program Files\\Blender Foundation\\Blender 4.0\\blender.exe',
        ]
        
        blender_cmd = None
        for path in blender_paths:
            try:
                result = subprocess.run([path, '--version'], capture_output=True, text=True, timeout=10)
                if result.returncode == 0:
                    blender_cmd = path
                    break
            except (subprocess.TimeoutExpired, FileNotFoundError, OSError):
                continue
        
        if not blender_cmd:
            return {'success': False, 'error': 'Blender not found'}
        
        try:
            # Write script to temporary file
            temp_script = Path(self.blend_path.parent) / 'temp_test_script.py'
            with open(temp_script, 'w') as f:
                f.write(script_content)
            
            # Run Blender script
            cmd = [blender_cmd, '--background', '--python', str(temp_script)]
            result = subprocess.run(cmd, capture_output=True, text=True, timeout=60)
            
            # Clean up temp file
            temp_script.unlink(missing_ok=True)
            
            if result.returncode == 0:
                return {'success': True, 'output': result.stdout}
            else:
                return {'success': False, 'error': result.stderr}
                
        except subprocess.TimeoutExpired:
            return {'success': False, 'error': 'Script timed out'}
        except Exception as e:
            return {'success': False, 'error': str(e)}
    
    def generate_report(self) -> str:
        """Generate a comprehensive test report."""
        report = []
        report.append("🧪 BLEND FILE TEST REPORT")
        report.append("=" * 50)
        report.append(f"📁 File: {self.blend_path}")
        report.append(f"📊 File Size: {self.test_results.get('file_size', 0) / 1024 / 1024:.2f} MB")
        report.append("")
        
        # Test Results Summary
        report.append("📋 TEST RESULTS SUMMARY")
        report.append("-" * 30)
        report.append(f"✅ File Exists: {self.test_results['file_exists']}")
        
        if self.test_results['scene_structure']:
            scene_data = self.test_results['scene_structure']
            report.append(f"🏗️ Objects: {len(scene_data.get('objects', []))}")
            report.append(f"🎨 Materials: {len(scene_data.get('materials', []))}")
            report.append(f"💡 Lights: {len(scene_data.get('lights', []))}")
            report.append(f"📷 Cameras: {len(scene_data.get('cameras', []))}")
        
        if self.test_results['animations']:
            animation_data = self.test_results['animations']
            report.append(f"🎬 Actions: {len(animation_data.get('actions', []))}")
        
        if self.test_results['performance']:
            perf = self.test_results['performance']
            report.append(f"⚡ Polygons: {perf.get('total_polygons', 0)}")
            report.append(f"🔑 Shape Keys: {perf.get('total_shape_keys', 0)}")
        
        report.append("")
        
        # Quality Issues
        if self.test_results['quality_issues']:
            report.append("⚠️ QUALITY ISSUES")
            report.append("-" * 20)
            for issue in self.test_results['quality_issues']:
                report.append(f"• {issue}")
            report.append("")
        
        # Recommendations
        if self.test_results['recommendations']:
            report.append("💡 RECOMMENDATIONS")
            report.append("-" * 20)
            for rec in self.test_results['recommendations']:
                report.append(f"• {rec}")
            report.append("")
        
        # Overall Assessment
        issue_count = len(self.test_results['quality_issues'])
        if issue_count == 0:
            report.append("🎉 OVERALL ASSESSMENT: EXCELLENT")
            report.append("No issues found. Blend file is ready for production!")
        elif issue_count <= 3:
            report.append("✅ OVERALL ASSESSMENT: GOOD")
            report.append("Minor issues found. Consider addressing recommendations.")
        elif issue_count <= 6:
            report.append("⚠️ OVERALL ASSESSMENT: FAIR")
            report.append("Several issues found. Address recommendations before production.")
        else:
            report.append("❌ OVERALL ASSESSMENT: NEEDS IMPROVEMENT")
            report.append("Multiple issues found. Significant improvements needed.")
        
        return "\n".join(report)


def test_blend_file(blend_path: str) -> Dict[str, Any]:
    """Test a blend file and return comprehensive results."""
    tester = BlendFileTester(blend_path)
    results = tester.run_comprehensive_test()
    report = tester.generate_report()
    
    print("\n" + report)
    
    return {
        'results': results,
        'report': report,
        'passed': len(results['quality_issues']) <= 3
    }


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python blend_file_tester.py <blend_file_path>")
        sys.exit(1)
    
    blend_path = sys.argv[1]
    test_blend_file(blend_path)
